-- Table: public.artists
CREATE TABLE IF NOT EXISTS public.artists
(
    birthdate date,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    firstname character varying(60) COLLATE pg_catalog."default",
    lastname character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT artists_pkey PRIMARY KEY (id)
)


-- Table: public.localities
CREATE TABLE IF NOT EXISTS public.localities
(
    postal_code character varying(6) COLLATE pg_catalog."default",
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    locality character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT localities_pkey PRIMARY KEY (id)
)


-- Table: public.prices
CREATE TABLE IF NOT EXISTS public.prices
(
    end_date date,
    price real NOT NULL,
    start_date date,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT prices_pkey PRIMARY KEY (id)
)


-- Table: public.roles
CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    role character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
)


-- Table: public.types
CREATE TABLE IF NOT EXISTS public.types
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT types_pkey PRIMARY KEY (id)
)

-- Table: public.users
CREATE TABLE IF NOT EXISTS public.users
(
    language character varying(2) COLLATE pg_catalog."default",
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    login character varying(30) COLLATE pg_catalog."default" NOT NULL,
    firstname character varying(60) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(60) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_login_key UNIQUE (login)
)