INSERT INTO `price_shows` (`price_id`, `show_id`)
VALUES
    (1, 1),  -- VIP pour "Sting en Concert à Paris"
    (2, 1),  -- Rang 1 pour "Sting en Concert à Paris"
    (3, 1),  -- Standard pour "Sting en Concert à Paris"
    (4, 2),  -- Rang 2 pour "Emma Watson dans “La Belle et la Bête”"
    (5, 2),  -- Privé pour "Emma Watson dans “La Belle et la Bête”"
    (6, 3),  -- Rang 3 pour "Sasha Waltz - Danse Contemporaine"
    (7, 3),  -- Premium pour "Sasha Waltz - Danse Contemporaine"
    (8, 4),  -- Rang 1 Réduit pour "David Copperfield - Magie Illusionniste"
    (9, 4),  -- VIP Réduit pour "David Copperfield - Magie Illusionniste"
    (10, 5), -- Rang 4 pour "Ariana Grande en Concert à Nice"
    (1, 6),  -- VIP pour "Quentin Tarantino présente ses Films à Paris"
    (2, 6),  -- Rang 1 pour "Quentin Tarantino présente ses Films à Paris"
    (3, 7),  -- Standard pour "Banksy – Art Contemporain"
    (4, 7),  -- Rang 2 pour "Banksy – Art Contemporain"
    (5, 8),  -- Privé pour "Misty Copeland – Ballet Classique"
    (6, 8),  -- Rang 3 pour "Misty Copeland – Ballet Classique"
    (7, 9),  -- Premium pour "Lorde en Concert à Toulouse"
    (8, 9),  -- Rang 1 Réduit pour "Lorde en Concert à Toulouse"
    (9, 10), -- VIP Réduit pour "Gad Elmaleh – Humoriste à Nantes"
    (10, 10); -- Rang 4 pour "Gad Elmaleh – Humoriste à Nantes"