INSERT INTO `types` (`type`)
VALUES
    ('Comédienne'),
    ('Comédien'),
    ('Costumière'),
    ('Metteur en scène'),
    ('Choregraphe'),
    ('Danseur'),
    ('Danseuse'),
    ('Assistance de direction artistique'),
    ('Réalisatrice'),
    ('Acteur principal'),
    ('Actrice principal'),
    ('Compositrice'),
    ('Compositeur'),
    ('Scénographe'),
    ('Musicienne'),
    ('Technicien lumière'),
    ('Rédatrice de texte'),
    ('Auteur'),
    ('Directeur technique'),
    ('Magicien'),
    ('Assistante'),
    ('Consultant en illusion visuelle'),
    ('Responsable des costumes'),
    ('Réalisateur'),
    ('Scénariste'),
    ('Chanteuse'),
    ('Interprète'),
    ('Directrice de la troupe'),
    ('Directeur musical'),
    ('Narateur'),
    ('Dramaturge'),
    ('Technicien vidéo'),
    ('Responsable des éclairages');