-- Table: public.artiste_type
CREATE TABLE IF NOT EXISTS public.artiste_type
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT artiste_type_pkey PRIMARY KEY (id)
);


-- Table: public.artiste_type_show
CREATE TABLE IF NOT EXISTS public.artiste_type_show
(
    id bigint NOT NULL,
    CONSTRAINT artiste_type_show_pkey PRIMARY KEY (id)
);


-- Table: public.locations
CREATE TABLE IF NOT EXISTS public.locations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    phone character varying(30) COLLATE pg_catalog."default",
    designation character varying(60) COLLATE pg_catalog."default",
    slug character varying(60) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default",
    website character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT locations_pkey PRIMARY KEY (id, slug),
    CONSTRAINT locations_slug_key UNIQUE (slug)
);


-- Table: public.representation_reservation
CREATE TABLE IF NOT EXISTS public.representation_reservation
(
    quantity integer,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT representation_reservation_pkey PRIMARY KEY (id)
);


-- Table: public.representations
CREATE TABLE IF NOT EXISTS public.representations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    schedule timestamp(6) without time zone,
    CONSTRAINT representations_pkey PRIMARY KEY (id)
);


-- Table: public.reservations
CREATE TABLE IF NOT EXISTS public.reservations
(
    booking_date timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT reservations_pkey PRIMARY KEY (id)
);


-- Table: public.reviews
CREATE TABLE IF NOT EXISTS public.reviews
(
    stars smallint,
    validated boolean,
    create_at timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    update_ad timestamp(6) without time zone,
    review text COLLATE pg_catalog."default",
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);


-- Table: public.role_user
CREATE TABLE IF NOT EXISTS public.role_user
(
    id bigint NOT NULL,
    CONSTRAINT role_user_pkey PRIMARY KEY (id)
);

-- Table: public.shows
CREATE TABLE IF NOT EXISTS public.shows
(
    bookable boolean,
    duration smallint,
    created_in timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    slug character varying(60) COLLATE pg_catalog."default" NOT NULL,
    poster_url character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT shows_pkey PRIMARY KEY (id, slug),
    CONSTRAINT shows_slug_key UNIQUE (slug)
);